config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  get 'ipfs-upload', to: 'tokens#ipfsUpload'
  get 'latest-mint', to: 'tokens#latestMint'
  # get 'pages/mint'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"

  resources :pages
  resources :items, only: :index

  resources :buy

  resources :tokens do
    resources :sale, except: :index
  end

end

app/models/token.rb
class Token < ApplicationRecord
    has_one :list_token
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
    before_action :is_signed_in?

    def is_signed_in?
        if !user_signed_in?
            redirect_to new_user_registration_path	
        end
    end

    def create
        redirect_to ipfs_upload_path
    end

    def new 
    end

    def show
        @token = Token.find(params[:id])
        @listed = Token.find(params[:id]).list_token
        if(@listed.nil? || !@listed.is_listed)
            @sell = false
        elsif
            @sell = true
        end
        if(@token.owner == current_user.wallet_address)
            @owner = true
        elsif
            @owner = false
        end
    end

    def ipfsUpload
    end

    def latestMint
        @tokens = Token.all
        FetchLatestMintJob.perform_now("#{gon.collectiblesAddress}",@tokens.length)
        redirect_to items_path
    end
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/ipfsUpload.html.erb
<%# spinner %>
<div class="d-flex  align-items-center justify-content-center" style="height: 85vh" id="spinner">
  <button class="btn btn-danger" type="button" disabled>
    <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
    <span class="visually-hidden">Loading...</span>
  </button>
  <button class="btn btn-danger ms-2" type="button" disabled>
    <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
    Please Wait, Processing !! 
  </button>
</div>

app/views/tokens/new.html.erb
<div id="NFTMintingForm">
  <div class="col-md-6 offset-md-3 mt-5">
    <%= simple_form_for :form , :url=> tokens_path, method: :POST, id: 'formId' do |f|%>
      <%= f.input :name, :as=>:string, :label=>"NFT Name", input_html: { id: 'name' } %>
      <br>
      <%= f.input :Imgae, :as=>:file, :label=>"NFT Image", input_html: {id: "image"}%>
      <br>
      <%= f.input :Description , :as=>:text, :label=>"Description", input_html: {id: "description"}%>
      <br>
      <%= f.submit "Submit", class: 'btn btn-primary', id: 'submitBtn'%>
    <%end%>
  </div>
</div>

app/views/tokens/show.html.erb
<div class="container d-flex mt-sm-5 justify-content-center py-0 flex-column flex-sm-row w-sm-75 mx-auto" id="item">
  <div class="card w-75 w-sm-25 text-center align-self-center">
    <img src="<%= @token.image_uri %>" class="card-img-top img-fluid" alt="..." >
    <div class="card-body border border-top">
      <h5 class="card-title">Token#</h5>
      <h5 class="card-title" id="tokenID"><%=@token.token_id%></h5>
    </div>
  </div>
  <div class="border border-primary my-3 mx-sm-5 my-sm-0 d-none d-sm-block">
  </div>
  <div id="listingForm" class="align-self-center mt-3 mt-sm-0 align-self-sm-center w-sm-50 w-75">
    <h5 class="card-title pb-3">Name : <%=@token.name%></h5>
    <section class="pb-1">
      <h5 class="card-title">Description : </h5>
      <p class="lead">
        <%=@token.description%>
      </p>
      <% if(@sell)%>
        <h5 class="card-title">Listed Price : </h5>
        <p class="lead" id="listedPrice">
          <%=@listed.list_price%>
        </p>
        <p class="d-none" id="signature"><%=@listed.approval_signature%></p>
      <%end%>
    </section>
    <%# for owner %>
    <div class="w-100 w-sm-75">
      <% if(@sell && @owner)%>
        <%= link_to 'Cancel Sell', token_sale_path(@token,@listed),method: :delete,data:{turbo_method: :delete,turbo_confirm: "Are you sure?"} ,class: 'btn btn-secondary mt-3 mt-sm-5 text-center w-100 w-sm-50 fs-5 fw-semibold' %>
      <%elsif(!@sell && @owner)%>
        <%=link_to 'Listing', new_token_sale_path(@token) , class: 'btn btn-danger mt-3 mt-sm-5 text-center w-100 w-sm-50 fs-5 fw-semibold'%>
      <%end%>
    </div>
    <%# for buyer %>
    <div class="w-100 w-sm-75">
      <% if(@sell&& !@owner)%>
        <button id="buyBtn" class="btn btn-primary mt-3 mt-sm-5 text-center w-100 w-sm-50 fs-5 fw-semibold">Buy</button>
      <%end%>
    </div>
  </div>
</div>
<%# loading %>
<%= render 'shared/spinner'%>