config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  get 'ipfs-upload', to: 'tokens#ipfsUpload'
  get 'latest-mint', to: 'tokens#latestMint'
  # get 'pages/mint'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"

  resources :pages
  resources :items, only: :index

  resources :buy

  resources :tokens do
    resources :sale, except: :index
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list_token.rb
class ListToken < ApplicationRecord
    belongs_to :token
end

app/models/token.rb
class Token < ApplicationRecord
    has_one :list_token
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :validatable
         :trackable

  def password_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :setGonData
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def setGonData
        gon.web3StorageAPIKey= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDBFNTUyYmZEQWQ3Y2I0MjdkZDZlNTZkQzExNzg3N2M3NzY3ZGI5RTIiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NjYxNjkyMDI1MTYsIm5hbWUiOiJORlRfUHJvamVjdCJ9.QPYxmfbzubF1SPASlxj7LlazkQdBQPNs8oFNZmBwggs"
        gon.collectiblesAddress = "0x99d10E2B7067781FD1715A5D66fb9F7B4BEeaE10"
        gon.exchangeAddress="0xdaBF7C115546510B2f6AD08ec617Ecffeec40c6A"
    end

 
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:wallet_address])
    end
end

app/controllers/buy_controller.rb
class BuyController < ApplicationController
    def index
    end

    def new
        token = Token.find_by(token_id: params[:id])
        listing = ListToken.find_by(token_id: params[:id])
        token.update(owner: (current_user.wallet_address).downcase)
        listing.update(is_listed: false,approval_signature: nil)
        redirect_to items_path
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :is_signed_in?

    def is_signed_in?
        if !user_signed_in?
            redirect_to new_user_registration_path	
        end
    end

    def index
        @tokens= Token.includes(:list_token).where(tokens: {owner: current_user.wallet_address})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if(user_signed_in?)
       @tokens= Token.includes(:list_token).where(list_token: {is_listed: true}).where.not(tokens: {owner: current_user.wallet_address})
    else
      @tokens= Token.includes(:list_token).where(list_token: {is_listed: true})
    end
  end
end

app/controllers/sale_controller.rb
class SaleController < ApplicationController
    before_action :is_signed_in?

    def is_signed_in?
        if !user_signed_in?
            redirect_to new_user_registration_path	
        end
    end

    def create
        if((Token.find(params[:token_id]).list_token).nil?)
            ListToken.create(token_id: params[:token_id], list_price: params[:form][:list_price],approval_signature: params[:approvalSignature], is_listed: true)
            redirect_to token_path(params[:token_id])
        else
            list = ListToken.find_by(token_id: params[:token_id])
            list.update(list_price: params[:form][:list_price],approval_signature: params[:approvalSignature], is_listed: true)
            redirect_to token_path(params[:token_id])
        end
    end

    def new
        @token= Token.find(params[:token_id])
    end

    def destroy
        list = ListToken.find(params[:id])
        list.update(is_listed: false,approval_signature: nil)
        redirect_to token_path
    end 
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
    before_action :is_signed_in?

    def is_signed_in?
        if !user_signed_in?
            redirect_to new_user_registration_path	
        end
    end

    def create
        redirect_to ipfs_upload_path
    end

    def new 
    end

    def show
        @token = Token.find(params[:id])
        @listed = Token.find(params[:id]).list_token
        if(@listed.nil? || !@listed.is_listed)
            @sell = false
        elsif
            @sell = true
        end
        if(@token.owner == current_user.wallet_address)
            @owner = true
        elsif
            @owner = false
        end
    end

    def ipfsUpload
    end

    def latestMint
        @tokens = Token.all
        FetchLatestMintJob.perform_now("#{gon.collectiblesAddress}",@tokens.length)
        redirect_to items_path
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sale_helper.rb
module SaleHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NftWebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "master", "data-turbo-track": "reload" %>
  </head>
  <body>
    <div id="wrap">
      <%= render 'shared/navbar'%>
      <div id="container">
        <%# <p class="notice"><%= notice %></p>
      <%# <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</div>
<%= render 'shared/footer'%>
</body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <h1 class="">Listed NFTs</h1>
</div>
<div class="container mt-3 w-sm-75">
  <div class="row row-cols-1 row-cols-2 row-cols-md-4">
    <% @tokens.each do |token| %>
      <div class="col my-3">
        <div class="card h-100">
          <img class="card-img-top" src="<%=token.image_uri%>" alt="Card image cap" style="height:100%">
          <div class="card-body">
            <h5 class="card-title"><%=token.name%></h5>
          </div>
          <ul class="list-group list-group-flush">
          </ul>
          <div class="card-body d-flex justify-content-between mx-s-2">
            <h4>
              <small class="text-muted fs-5"><%=token.list_token.list_price%> ETH</small>
            </h4>
            <%= link_to 'Buy',token_path(token) ,class: 'btn btn-primary stretched-link'%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/mint.html.erb
<div id="NFTMintingForm">
  <div class="col-md-6 offset-md-3 mt-5">
    <%= simple_form_for :form , :url=> pages_path, method: :POST, id: 'formId' do |f|%>
      <%= f.input :name, :as=>:string, :label=>"NFT Name", input_html: { id: 'name' } %>
      <br>
      <%= f.input :Imgae, :as=>:file, :label=>"NFT Image", input_html: {id: "image"}%>
      <br>
      <%= f.input :Description , :as=>:text, :label=>"Description", input_html: {id: "description"}%>
      <br>
      <%= f.submit "Submit", class: 'btn btn-primary', id: 'submitBtn'%>
    <%end%>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class=" text-center text-lg-start sticky-bottom shadow-sm rounded-top" style="">
  <!-- Copyright -->
  <div class="text-center mt-2 fw-bolder d-flex justify-content-center" >
    <p class="mt-3">&copy; TECHBRAIN <%= Date.today.year %>All Rights Reserved</p>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">InfiniteTOK</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/items">Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/tokens/new">Mint NFT</a>
        </li>
      </ul>
      <ul class="navbar-nav d-flex justify-content-end">
        <li class="nav-item">
          <a class="nav-link" id="loginId" href="#"></a>
        </li>
        <%if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path ,data:{turbo_method: :delete}, class: 'nav-link',id: 'logoutId'%>
          </li>
        <%else%>
          <li class="nav-item">
            <%= link_to 'Log in', new_user_registration_path , class: 'nav-link'%>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_spinner.html.erb
<div class="d-flex  align-items-center justify-content-center d-none" id="spinner" style="height: 75vh" id="spinner">
  <button class="btn btn-danger" type="button" disabled>
    <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
    <span class="visually-hidden">Loading...</span>
  </button>
  <button class="btn btn-danger ms-2" type="button" disabled>
    <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
    Please Wait, Processing !! 
  </button>
</div>