config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  get 'ipfs-upload', to: 'tokens#ipfsUpload'
  get 'latest-mint', to: 'tokens#latestMint'
  # get 'pages/mint'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"

  resources :pages
  resources :items, only: :index

  resources :buy

  resources :tokens do
    resources :sale, except: :index
  end

end

app/controllers/sale_controller.rb
class SaleController < ApplicationController
    before_action :is_signed_in?

    def is_signed_in?
        if !user_signed_in?
            redirect_to new_user_registration_path	
        end
    end

    def create
        if((Token.find(params[:token_id]).list_token).nil?)
            ListToken.create(token_id: params[:token_id], list_price: params[:form][:list_price],approval_signature: params[:approvalSignature], is_listed: true)
            redirect_to token_path(params[:token_id])
        else
            list = ListToken.find_by(token_id: params[:token_id])
            list.update(list_price: params[:form][:list_price],approval_signature: params[:approvalSignature], is_listed: true)
            redirect_to token_path(params[:token_id])
        end
    end

    def new
        @token= Token.find(params[:token_id])
    end

    def destroy
        list = ListToken.find(params[:id])
        list.update(is_listed: false,approval_signature: nil)
        redirect_to token_path
    end 
end

app/helpers/sale_helper.rb
module SaleHelper
end

app/views/sale/new.html.erb
<div class="mx-3" style="margin-top:6rem" id="sellWizard">
  <h1 class="text-center font-monospace fw-semibold">Sell Item #
    <p id="tokenID"> <%=@token.token_id%></p>
  </h1>
  <div class="shadow-lg p-3 mb-5 bg-body rounded w-sm-50 mx-auto mt-4 mt-sm-5">
    <div class="container d-flex mt-sm-4 justify-content-center py-5 flex-column flex-sm-row w-sm-75 mx-auto" >
      <div class="w-100 w-sm-75">
        <%= simple_form_for :form,url: token_sale_index_path(@token.token_id),id: 'sellForm' do |f| %>
          <%= f.input :list_price, :as => :float,:label => 'Price', placeholder: '0.0 ETH' %>
          <%=f.submit 'List This Item' , class: 'btn btn-danger mt-3 mt-sm-4 text-center w-100 w-sm-50 fs-5 fw-semibold',id: 'listingBtn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%# loading %>
<%= render 'shared/spinner'%>